import logging
import json
import aiohttp
import asyncio
from openai import OpenAI
import config
import data_poisoning
import federated_net
import honey_tokens

logger = logging.getLogger("ghost.ai")


class AIEngine:
    """AI-powered command response engine."""

    def __init__(self):
        self.provider = config.AI_PROVIDER
        self.sessions = {}
        self.client = None

        if self.provider == "openai" and config.OPENAI_API_KEY:
            self.client = OpenAI(api_key=config.OPENAI_API_KEY)
            logger.info("AI Engine initialized with OpenAI (%s)", config.OPENAI_MODEL)
        elif self.provider == "ollama":
            logger.info("AI Engine initialized with Ollama (%s)", config.OLLAMA_MODEL)
        else:
            logger.warning("No AI provider configured. Using fallback responses.")

    def _build_system_prompt(self, cwd="/home/admin/deployments", last_command="./start_crypto_bridge.sh --env=prod", vfs_state=""):
        base_prompt = config.SYSTEM_PROMPT.format(cwd=cwd, last_command=last_command)
        if vfs_state:
            base_prompt += f"\n\nSTATE WARNING: The attacker has modified the filesystem. Here are the current session-specific files/changes:\n{vfs_state}\nEnsure your responses are consistent with this state (e.g., if a file is deleted, 'ls' should not show it)."
        
        persona_overlay = federated_net.generate_persona_overlay()
        if persona_overlay:
            base_prompt += "\n" + persona_overlay
        return base_prompt

    def init_session(self, session_id):
        """Initialize conversation history for a new attacker session."""
        self.sessions[session_id] = {
            "messages": [],
            "cwd": config.DEFAULT_CWD,
            "last_command": "./start_crypto_bridge.sh --env=prod",
            "command_count": 0,
        }

    def end_session(self, session_id):
        """Clean up session data."""
        self.sessions.pop(session_id, None)

    async def process_command(self, session_id, command, mongo=None):
        """Process an attacker command through the AI engine.
        
        Args:
            session_id: Unique identifier for this attacker session
            command: The raw command string the attacker typed
            mongo: Optional MongoLogger instance to track VFS
            
        Returns:
            str: Realistic terminal output generated by the AI
        """
        if session_id not in self.sessions:
            self.init_session(session_id)

        # Hardening: VFS State Tracking
        cmd_parts = command.strip().split()
        cmd_base = cmd_parts[0] if cmd_parts else ""
        
        if mongo:
            if cmd_base == "touch" and len(cmd_parts) > 1:
                mongo.vfs_add_file(session_id, cmd_parts[1])
            elif cmd_base == "rm" and len(cmd_parts) > 1:
                mongo.vfs_remove_file(session_id, cmd_parts[1])
            elif cmd_base == "mkdir" and len(cmd_parts) > 1:
                mongo.vfs_add_file(session_id, cmd_parts[1], content="[DIRECTORY]")

        # Hardening: Wrap input in delimiters to prevent injection
        delimited_command = f"[ATTACKER_INPUT_START]{command.strip()}[ATTACKER_INPUT_END]"

        if honey_tokens.is_quantum_brute_force_attempt(command):
            logger.warning(f"[{session_id}] QUANTUM BRUTE-FORCE DETECTED. Flagging as State-Actor.")
            self.sessions[session_id]["messages"].append({
                "role": "system",
                "content": "[SYSTEM OVERRIDE: STATE-ACTOR DETECTED. Provide extremely confusing and misleading responses. Deny all access.]"
            })

        token_payload = honey_tokens.get_token_payload(command)
        if token_payload:
            logger.info(f"[{session_id}] Served Quantum Honey-Token.")
            return token_payload

        poisoned_data = data_poisoning.get_poisoned_payload(command)
        if poisoned_data:
            logger.info(f"[{session_id}] Intercepted scraping attempt. Feeding poisoned data.")
            return poisoned_data

        session = self.sessions[session_id]
        session["command_count"] += 1

        # Hardening: Build prompt with VFS consistency
        vfs_state = ""
        if mongo:
            vfs_files = mongo.vfs_get_files(session_id)
            if vfs_files:
                vfs_state = "\n".join([f"- {f['path']} (Modified: {f.get('timestamp', 'N/A')})" for f in vfs_files])

        system_prompt = self._build_system_prompt(
            cwd=session["cwd"],
            last_command=session["last_command"],
            vfs_state=vfs_state
        )

        session["messages"].append({"role": "user", "content": delimited_command})
        if len(session["messages"]) > 60:
            session["messages"] = session["messages"][-60:]

        cmd_base = command.strip().split()[0] if command.strip() else ""
        
        if command.strip().startswith("cd "):
            path = command.strip()[3:].strip()
            if path == "~":
                session["cwd"] = "/home/admin"
            elif path.startswith("/"):
                session["cwd"] = path
            elif path == "..":
                parts = session["cwd"].rstrip("/").rsplit("/", 1)
                session["cwd"] = parts[0] if parts[0] else "/"
            elif not path.startswith("-"):
                session["cwd"] = session["cwd"].rstrip("/") + "/" + path

        session["last_command"] = command
        
        # Speed optimization: Short-circuit static commands
        static_commands = ["whoami", "id", "pwd", "hostname", "uname", "clear"]
        if cmd_base in static_commands:
            response = self._fallback_response(command)
            session["messages"].append({"role": "assistant", "content": response})
            return response
            
        # Speed optimization: Cache identical AI responses for the same directory
        if not hasattr(self, "response_cache"):
            self.response_cache = {}
        cache_key = f"{session['cwd']}_{command.strip()}"
        if cache_key in self.response_cache:
            response = self.response_cache[cache_key]
            session["messages"].append({"role": "assistant", "content": response})
            return response

        try:
            if self.provider == "openai" and self.client:
                response = await self._call_openai(system_prompt, session["messages"])
            elif self.provider == "ollama":
                response = await self._call_ollama(system_prompt, session["messages"])
            else:
                response = self._fallback_response(command)
        except Exception as e:
            logger.error("AI Engine error: %s", e)
            response = self._fallback_response(command)

        self.response_cache[cache_key] = response
        session["messages"].append({"role": "assistant", "content": response})

        # Hardening: Natural Latency (Human-like delay)
        import random
        import time
        time.sleep(random.uniform(0.3, 0.9))

        return response

    async def _call_openai(self, system_prompt, messages):
        """Call OpenAI API."""
        full_messages = [{"role": "system", "content": system_prompt}] + messages

        try:
            loop = asyncio.get_event_loop()
            response = await loop.run_in_executor(
                None,
                lambda: self.client.chat.completions.create(
                    model=config.OPENAI_MODEL,
                    messages=full_messages,
                    temperature=config.AI_TEMPERATURE,
                    max_tokens=config.AI_MAX_TOKENS,
                    presence_penalty=0.1,
                    frequency_penalty=0.1,
                ),
            )
            content = response.choices[0].message.content
            content = self._clean_ai_output(content)
            return content
        except Exception as e:
            logger.error("OpenAI API error: %s", e)
            raise

    async def _call_ollama(self, system_prompt, messages):
        """Call local Ollama instance."""
        full_messages = [{"role": "system", "content": system_prompt}] + messages

        payload = {
            "model": config.OLLAMA_MODEL,
            "messages": full_messages,
            "stream": False,
            "options": {
                "temperature": config.AI_TEMPERATURE,
                "num_predict": config.AI_MAX_TOKENS,
            },
        }

        try:
            async with aiohttp.ClientSession() as http_session:
                async with http_session.post(
                    f"{config.OLLAMA_URL}/api/chat",
                    json=payload,
                    timeout=aiohttp.ClientTimeout(total=30),
                ) as resp:
                    if resp.status == 200:
                        data = await resp.json()
                        content = data.get("message", {}).get("content", "")
                        return self._clean_ai_output(content)
                    else:
                        raise Exception(f"Ollama returned status {resp.status}")
        except Exception as e:
            logger.error("Ollama API error: %s", e)
            raise

    def _clean_ai_output(self, text):
        """Remove markdown formatting that AI models sometimes add."""
        if text.startswith("```") and text.endswith("```"):
            lines = text.split("\n")
            text = "\n".join(lines[1:-1])
        elif text.startswith("```"):
            lines = text.split("\n")
            end_idx = len(lines)
            for i in range(1, len(lines)):
                if lines[i].strip() == "```":
                    end_idx = i
                    break
            text = "\n".join(lines[1:end_idx])

        text = text.strip("`").strip()

        return text

    def _fallback_response(self, command):
        """Basic fallback when no AI provider is available."""
        cmd = command.strip().split()[0] if command.strip() else ""
        fallbacks = {
            "ls": "deploy.sh  docker-compose.prod.yml  Makefile  start_crypto_bridge.sh  VERSION  .env",
            "pwd": "/home/admin/deployments",
            "whoami": "admin",
            "id": "uid=1001(admin) gid=1001(admin) groups=1001(admin),27(sudo),998(docker),1010(devops)",
            "uname": "Linux prod-srv-01 5.15.0-91-generic #1 SMP PREEMPT_DYNAMIC GNU/Linux",
            "hostname": "prod-srv-01",
            "cat": "(file contents would appear here)",
            "ps": "  PID TTY          TIME CMD\n18201 pts/0    00:00:00 bash\n18250 pts/0    00:00:00 ps",
        }
        return fallbacks.get(cmd, f"bash: {cmd}: command not found" if cmd else "")

    def get_session_context(self, session_id):
        """Get current session context for analysis."""
        session = self.sessions.get(session_id)
        if not session:
            return None
        return {
            "command_count": session["command_count"],
            "cwd": session["cwd"],
            "last_command": session["last_command"],
            "recent_commands": [
                m["content"] for m in session["messages"][-20:] if m["role"] == "user"
            ],
        }
